---
functional:
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность принимать участие в игре/чемпионате
  - Пользователь должен иметь возможность видеть решение задачи противника
  - Пользователь должен иметь возможность редактировать личный профиль

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - У пользователя должна быть возможность зарегистрироваться/авторизоваться
  - Пользователи должны соблюдать принципы сообщества при общении в чате
  - У пользователя должна быть возможность обратиться в службу тех. поддержке
