---
functional:
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность выбрать уровень сложности, тип игры, время и саму задачу.
  - Пользователь должен иметь возможность приглашать друга в игру
  - Пользователь должен иметь возможность видеть решение задачи противника
  - Пользователь должен иметь возможность присоединиться к игре
  - Пользователь должен иметь возможность отказаться от приглашения на игру
  - Пользователь должен иметь возможность сдаться в  процессе игры
  - Пользователь должен иметь возможность прервать игру 
  - Пользователь должен иметь возможность продолжить прерванную игру 
  - Пользователь должен иметь возможность редактировать личный профиль

non-functional:
  - У пользователя должна быть возможность зарегистрироваться/авторизоваться
  - Пользователь 
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - Пользователи должны соблюдать принципы сообщества при общении в чате
  - У пользователя должна быть возможность обратиться в службу тех. поддержке



